### ISSUE TITLE
Поиск по названию папки

### ISSUE THREAD

**Issue by LeonusDH** [fzfking/RimTrans#1]
Можно ли сделать поиск не только по названию мода но и по названию папки?

**Comment by fzfking** [comment]
@LeonusDH  Привет, сорри, что с такой задержкой отвечаю, не было уведы и поэтому не увидел даже что появилось issue. Да, хорошо, добавлю.

**Comment by LeonusDH** [comment]
@fzfking, ничего страшного. Я успел уже забыть даже об этом issue, если быть до конца честным.

**Comment by fzfking** [comment]
Ну в любом случае добавлено теперь)
